### PR TITLE
Use application name for icons when not provided by audio engine

### PR DESCRIPTION
**Pull request by Janhouse**
This will set the icon string to lower-case application name. It helps for applications which do not provide the icon to audio engine (for example Firefox).
`/usr/share/icons/...` contains lots of application icons in lower case so this should work for many applications.

If the icon is set properly, it will use that instead.

Example of fixed Firefox icon, while Spotify icon comes from pipewire:

image

### CODE REVIEW

**Comment by Rayzeq** [comment]
It's a good idea to fix the icons, but I don't think we should limit to `applications-multimedia`. Opera uses `chromium-browser` and ncspot uses `audio`. I think we should detect whether the icon name provided exists, and if not (100% of the cases I've encountered so far) use the application name.
I already asked in the IRC chat if there is an easy way to do that (so far I only found [`St.TextureCache.load_gicon`](https://gjs-docs.gnome.org/st12~12/st.texturecache#method-load_gicon), but it needs informations that we can't just leave blank), so I'll wait for an answer.

**Comment by Janhouse** [comment]
@Rayzeq I updated my branch to use [`St.IconTheme.has_icon`](https://gjs-docs.gnome.org/st12~12/st.icontheme#method-has_icon)
Seems to work fine with the applications I use.

**Comment by Janhouse** [comment]
Tried it also with `ncspot`, `opera`, `amberol` (mentioned in extension comments), worked correctly for all of them.

**Comment by Rayzeq** [comment]
Nice, this works well.

**Pull request merged**
